version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    command: npm run start:dev

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"